
server:
  port: 8100

spring:
  application:
    name: apigateway
#  config:
#    import: optional:configserver:http://localhost:8999
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: microservice-utilisateurs-id
          uri: http://localhost:8101/ #http://mutilisateurs-service:8101/
          predicates:
            - Path=/utilisateurs/**
          filters:
            - AuthorizationFilter
        - id: microservice-demandes-id
          uri: http://localhost:8102/ #http://mutilisateurs-service:8101/
          predicates:
            - Path=/demandes/**
          filters:
            - AuthorizationFilter
        - id: microservice-rest-notifications-id
          uri: http://localhost:8103/ #http://mutilisateurs-service:8101/
          predicates:
            - Path=/notifications/**
        - id: microservice-notifications-id
          uri: ws://localhost:8103/ #http://mutilisateurs-service:8101/
          predicates:
            - Path=/notifications-endpoint/**
        - id: microservice-infractions-id
          uri: http://localhost:8104/ #http://mutilisateurs-service:8101/
          predicates:
            - Path=/infractions/**
          filters:
            - AuthorizationFilter
      default-filters:
        - AddResponseHeader=Routed, Yes

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
